import '../scss/style.scss';
import '../js/readMore';
import '../js/swiper';
import '../js/swiperReadMore';
import '../js/swiper-2';
import '../js/swiper-2ReadMore';
import '../js/swiper-3';
import '../js/main-menu__modal';
import '../js/feedback-modal';
import '../js/call-modal';
console.log('Works!');
